name: media_toolkit
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  protobuf: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.2
  convert: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: chat.owl.media_toolkit
        pluginClass: MediaToolkitPlugin
      ios:
        pluginClass: MediaToolkitPlugin

ffigen:
  output: "lib/ffi.dart"
  name: "RawMediaToolkit"
  description: "Owlchat Media Toolkit Bindings"
  sort: true
  comments:
    style: any
    length: full
  compiler-opts:
    - "-DDART"
  headers:
    entry-points:
      - "ffi/binding.h"
    include-directives:
      - "**binding.h"
