name: media_toolkit
description: A Rust Powered Media toolkit for Flutter and Dart Apps.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi:
dev_dependencies:
  pedantic: ^1.9.0
  ffigen: ^1.0.5

ffigen:
  output: 'lib/ffi.dart'
  name: 'RawMediaToolkit'
  description: 'Owlchat Media Toolkit Binding'
  array-workaround: false
  sort: true
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - 'native/toolkit/binding.h'
    include-directives:
      - '**binding.h'
