[package]
name = "media-toolkit"
version = "0.1.0"
edition = "2021"

[dependencies]
blurhash = "0.1"
image = { version = "0.23", default-features = false, features = [
  "jpeg",
  "png",
  "webp",
] }
kamadak-exif = "0.5"
